import { createHash } from "node:crypto";
import type { SkillCategory } from "@/modules/skill";

export type BaselinePromptCase = {
  readonly prompt: string;
  readonly expected: "fire" | "silent";
};

export type BaselineSkillProvenance = {
  readonly authoringTool: string;
  readonly authoredAt: string;
  readonly sourcePrompt: string;
};

export type BaselineSkillCorpusEntry = {
  readonly id: string;
  readonly version: 1;
  readonly name: string;
  readonly description: string;
  readonly source: string;
  readonly contentHash: string;
  readonly promptBattery: readonly BaselinePromptCase[];
  readonly provenance: BaselineSkillProvenance;
};

type CorpusSeed = Omit<BaselineSkillCorpusEntry, "contentHash">;

const AUTHORING_TOOL = "Anthropic skill-creator pattern, curated fixture";
const AUTHORED_AT = "2026-07-03";
const EXPANSION_AUTHORED_AT = "2026-07-12";

const seeds = [
  skill({
    id: "inbox-triage",
    name: "inbox-triage",
    description: "Triage unread business email into reply, delegate, schedule, archive, or urgent follow-up.",
    category: "email",
    tags: ["triage", "inbox", "prioritisation"],
    sourcePrompt: "Create an inbox triage skill for an SMB owner handling unread email.",
    body: [
      "## When to use",
      "Use this skill when the user asks to sort, prioritise, or decide next actions for unread business email.",
      "",
      "Do not use it for writing a full outbound campaign, managing calendar conflicts, or extracting data from attachments.",
      "",
      "## Workflow",
      "1. Read the sender, subject, received time, thread context, and any supplied labels.",
      "2. Classify each message as reply, delegate, schedule, archive, or urgent follow-up.",
      "3. Call out missing context before recommending a destructive action.",
      "4. Present a compact queue with the reason for each label and the next action.",
      "",
      "## Guardrails",
      "- Never send, delete, or forward email without explicit confirmation.",
      "- Keep private customer details out of summaries unless the user asked for them.",
    ],
    positives: [
      "Sort my unread customer emails and tell me which need a reply today.",
      "Triage this inbox export into urgent follow-ups and archive candidates.",
      "Which of these new emails should I delegate to operations?",
    ],
    negatives: [
      "Draft a newsletter for every customer on my list.",
      "Find a time for the client call next week.",
      "Extract invoice totals from these PDFs.",
    ],
  }),
  skill({
    id: "meeting-scheduler",
    name: "meeting-scheduler",
    description: "Find suitable meeting times, prepare scheduling options, and draft concise calendar invitations.",
    category: "calendar",
    tags: ["scheduling", "meetings", "availability"],
    sourcePrompt: "Create a meeting scheduling skill for a busy small-business operator.",
    body: [
      "## When to use",
      "Use this skill when the user needs help arranging, moving, or confirming a meeting.",
      "",
      "Do not use it for taking meeting notes, summarising transcripts, or planning an event agenda from scratch.",
      "",
      "## Workflow",
      "1. Identify attendees, duration, timezone, deadline, and any immovable constraints.",
      "2. Compare the supplied availability and propose the smallest useful set of options.",
      "3. Draft the invite title, agenda bullets, location or link, and confirmation message.",
      "4. Ask before committing calendar changes or sending invitations.",
      "",
      "## Guardrails",
      "- Preserve timezone names in user-facing options.",
      "- Flag conflicts instead of silently overriding them.",
    ],
    positives: [
      "Find three times for a 30 minute client meeting next week.",
      "Move tomorrow's supplier call and draft the calendar update.",
      "Schedule a kickoff with Alex and Priya before Friday.",
    ],
    negatives: [
      "Summarise the notes from yesterday's client call.",
      "Triage my unread email by urgency.",
      "Write a data extraction schema for receipts.",
    ],
  }),
  skill({
    id: "receipt-expense-logger",
    name: "receipt-expense-logger",
    description: "Turn receipt details into expense records with category, tax, reimbursement, and review flags.",
    category: "finance",
    tags: ["expenses", "receipts", "bookkeeping"],
    sourcePrompt: "Create a receipt expense logging skill for SMB bookkeeping.",
    body: [
      "## When to use",
      "Use this skill when the user provides receipts, transaction notes, or reimbursement details to record expenses.",
      "",
      "Do not use it for producing invoices, reconciling a full bank feed, or giving tax advice.",
      "",
      "## Workflow",
      "1. Extract merchant, date, currency, total, tax, payment method, and business purpose.",
      "2. Assign a likely category and confidence level.",
      "3. Mark missing values and duplicates for review.",
      "4. Return ledger-ready rows plus questions needed before submission.",
      "",
      "## Guardrails",
      "- Do not invent tax treatment or compliance claims.",
      "- Keep personal purchases separate from business expenses.",
    ],
    positives: [
      "Log these lunch receipts and flag which ones need a business purpose.",
      "Categorise this pile of travel expenses for reimbursement.",
      "Turn this receipt text into expense rows with GST separated.",
    ],
    negatives: [
      "Create an invoice for my consulting hours.",
      "Summarise a policy document into bullets.",
      "Schedule a finance review meeting.",
    ],
  }),
  skill({
    id: "invoice-drafter",
    name: "invoice-drafter",
    description: "Draft invoice line items from billable work, rates, dates, terms, and client details.",
    category: "finance",
    tags: ["invoicing", "billing", "payment-terms"],
    sourcePrompt: "Create an invoice drafting skill for service businesses.",
    body: [
      "## When to use",
      "Use this skill when the user needs an invoice draft from supplied work, rates, client details, or timesheets.",
      "",
      "Do not use it for collecting payment, changing accounting records, or logging reimbursable receipts.",
      "",
      "## Workflow",
      "1. Confirm client name, invoice period, currency, payment terms, and tax requirements.",
      "2. Convert work notes into clear line items with quantities, rates, and totals.",
      "3. Highlight assumptions and missing details before finalising.",
      "4. Provide a client-ready invoice draft and a short covering note.",
      "",
      "## Guardrails",
      "- Never claim an invoice has been sent or paid.",
      "- Keep calculations visible so the user can check them.",
    ],
    positives: [
      "Draft an invoice for 12 hours of consulting at 180 dollars per hour.",
      "Turn these billable work notes into invoice line items.",
      "Prepare a client invoice with net 14 payment terms.",
    ],
    negatives: [
      "Categorise these cafe receipts for bookkeeping.",
      "Write a social media post for our launch.",
      "Review this contract for risky clauses.",
    ],
  }),
  skill({
    id: "policy-summariser",
    name: "policy-summariser",
    description: "Summarize policy or procedure documents into obligations, deadlines, owners, and open questions.",
    category: "documents",
    tags: ["summarisation", "policies", "compliance"],
    sourcePrompt: "Create a document summarisation skill for business policies and procedures.",
    body: [
      "## When to use",
      "Use this skill when the user asks for a plain-language summary of a policy, procedure, or operating document.",
      "",
      "Do not use it for legal advice, contract negotiation, or drafting new policy from scratch.",
      "",
      "## Workflow",
      "1. Identify the document purpose, audience, effective date, and scope.",
      "2. Summarise obligations, deadlines, exceptions, and responsible roles.",
      "3. Separate facts from interpretation and list unclear clauses.",
      "4. End with actions the user can take next.",
      "",
      "## Guardrails",
      "- Preserve exact wording for must, must not, and deadline language when it matters.",
      "- Say when a legal or compliance professional should review.",
    ],
    positives: [
      "Summarise this leave policy into manager obligations.",
      "What are the deadlines and responsibilities in this procedure?",
      "Condense this vendor policy into actions for our team.",
    ],
    negatives: [
      "Draft an invoice for this month's work.",
      "Sort my inbox by which emails need replies.",
      "Generate captions for a product launch.",
    ],
  }),
  skill({
    id: "customer-follow-up",
    name: "customer-follow-up",
    description: "Draft customer follow-up messages from context, desired outcome, tone, and timing.",
    category: "sales",
    tags: ["follow-up", "customers", "outreach"],
    sourcePrompt: "Create a customer follow-up drafting skill for sales and support.",
    body: [
      "## When to use",
      "Use this skill when the user needs a one-to-one follow-up message for a customer, lead, or support contact.",
      "",
      "Do not use it for bulk marketing campaigns, internal meeting scheduling, or CRM data cleanup.",
      "",
      "## Workflow",
      "1. Identify the relationship, previous interaction, objective, and any promised next step.",
      "2. Choose the shortest tone that fits the situation.",
      "3. Draft the message with a clear ask or next action.",
      "4. Offer a firmer or warmer variant when useful.",
      "",
      "## Guardrails",
      "- Do not promise discounts, timelines, or outcomes the user did not provide.",
      "- Keep sensitive account details out of the draft unless needed.",
    ],
    positives: [
      "Write a polite follow-up to a customer who missed our demo.",
      "Draft a support check-in after yesterday's repair visit.",
      "Follow up with this lead and ask whether they want a quote.",
    ],
    negatives: [
      "Create a weekly content calendar for LinkedIn.",
      "Classify these receipts by expense category.",
      "Summarise a procedure document for managers.",
    ],
  }),
  skill({
    id: "data-extraction-brief",
    name: "data-extraction-brief",
    description: "Define fields, examples, validation rules, and edge cases for extracting data from messy documents.",
    category: "analysis",
    tags: ["data-extraction", "schemas", "documents"],
    sourcePrompt: "Create a data extraction brief skill for forms, PDFs, and emails.",
    body: [
      "## When to use",
      "Use this skill when the user wants a structured extraction plan or schema for messy source documents.",
      "",
      "Do not use it for running the extraction, scraping websites, or interpreting legal meaning.",
      "",
      "## Workflow",
      "1. Identify the document type, business goal, and destination format.",
      "2. Define fields with types, examples, required status, and validation rules.",
      "3. List ambiguous cases and how to handle missing or conflicting values.",
      "4. Return a compact extraction brief the user can hand to an agent or analyst.",
      "",
      "## Guardrails",
      "- Do not invent source values.",
      "- Mark personally sensitive fields so the user can apply access controls.",
    ],
    positives: [
      "Design a schema to extract order numbers and totals from supplier PDFs.",
      "What fields should we pull from these application emails?",
      "Make an extraction brief for these onboarding forms.",
    ],
    negatives: [
      "Summarise this policy in plain language.",
      "Draft a customer apology email.",
      "Book a meeting with the supplier.",
    ],
  }),
  skill({
    id: "job-posting-drafter",
    name: "job-posting-drafter",
    description: "Draft practical job postings from role outcomes, must-haves, schedule, location, and hiring constraints.",
    category: "hiring",
    tags: ["job-postings", "recruitment"],
    sourcePrompt: "Create a hiring job-post drafting skill for a small team.",
    body: [
      "## When to use",
      "Use this skill when the user needs a clear job posting or role advert from supplied hiring details.",
      "",
      "Do not use it for screening candidates, writing performance reviews, or negotiating offers.",
      "",
      "## Workflow",
      "1. Clarify role outcomes, required skills, nice-to-haves, location, schedule, and pay range if provided.",
      "2. Draft a plain-language posting with responsibilities, requirements, and application steps.",
      "3. Remove exclusionary or inflated wording unless the user explicitly needs it.",
      "4. Provide a short social-share version.",
      "",
      "## Guardrails",
      "- Do not invent salary, visa, or legal requirements.",
      "- Flag wording that could be discriminatory or misleading.",
    ],
    positives: [
      "Draft a job ad for a part-time operations assistant.",
      "Turn these role notes into a hiring post.",
      "Write a practical job posting for a cafe manager.",
    ],
    negatives: [
      "Screen these candidate resumes and rank them.",
      "Write a customer follow-up email.",
      "Log these business expenses.",
    ],
  }),
  skill({
    id: "brand-social-drafter",
    name: "brand-social-drafter",
    description: "Draft short social posts from campaign context, audience, channel, offer, and brand voice notes.",
    category: "marketing",
    tags: ["social-media", "copywriting", "campaigns"],
    sourcePrompt: "Create a social post drafting skill for small-business marketing.",
    body: [
      "## When to use",
      "Use this skill when the user asks for short social media copy for a known brand, campaign, or announcement.",
      "",
      "Do not use it for one-to-one customer follow-up, long-form blog posts, or paid ad strategy.",
      "",
      "## Workflow",
      "1. Identify channel, audience, offer, deadline, call to action, and voice constraints.",
      "2. Draft two or three concise options with different angles.",
      "3. Include hashtag or formatting suggestions only when relevant to the channel.",
      "4. Note any missing claim, price, or availability detail before publication.",
      "",
      "## Guardrails",
      "- Do not make factual claims the user did not supply.",
      "- Avoid manipulative urgency unless the user provided a real deadline.",
    ],
    positives: [
      "Write three Instagram captions for our winter menu launch.",
      "Draft a LinkedIn post announcing the new service package.",
      "Make a short social post for this weekend's sale.",
    ],
    negatives: [
      "Follow up with a customer after a support ticket.",
      "Summarise a policy document.",
      "Create fields for extracting invoice data.",
    ],
  }),
  skill({
    id: "contract-risk-spotter",
    name: "contract-risk-spotter",
    description: "Spot practical business risks in a contract excerpt and prepare questions for professional review.",
    category: "legal",
    tags: ["contracts", "risk-review"],
    sourcePrompt: "Create a contract risk spotting skill for non-lawyer business users.",
    body: [
      "## When to use",
      "Use this skill when the user wants practical risks, obligations, or questions from a contract excerpt.",
      "",
      "Do not use it for legal advice, negotiation strategy, or final approval of a contract.",
      "",
      "## Workflow",
      "1. Identify parties, dates, payment terms, renewal, termination, liability, confidentiality, and deliverables.",
      "2. List practical risks in plain language with the clause or phrase that raised each issue.",
      "3. Separate business questions from legal-review questions.",
      "4. Suggest information the user should gather before asking a professional.",
      "",
      "## Guardrails",
      "- Say clearly that the output is not legal advice.",
      "- Preserve exact clause wording when quoting risk triggers.",
    ],
    positives: [
      "Review this contract excerpt for practical business risks.",
      "What questions should I ask a lawyer about this supplier agreement?",
      "Spot obligations and renewal risks in these terms.",
    ],
    negatives: [
      "Summarise our internal leave policy for managers.",
      "Draft a social caption for a sale.",
      "Schedule a meeting with the supplier.",
    ],
  }),
  skill({
    id: "calendar-week-planner",
    name: "calendar-week-planner",
    description: "Plan a working week from tasks, priorities, appointments, and deadlines into a realistic day-by-day schedule.",
    category: "calendar",
    tags: ["planning", "prioritisation", "time-management"],
    sourcePrompt: "Create a weekly calendar planning skill for a busy small-business owner.",
    authoredAt: EXPANSION_AUTHORED_AT,
    body: [
      "## When to use",
      "Use this skill when the user wants to plan a day or week from their tasks, priorities, appointments, and deadlines.",
      "",
      "Do not use it for arranging a single meeting with other attendees, triaging email, or logging completed work.",
      "",
      "## Workflow",
      "1. Read the task list, fixed appointments, deadlines, and stated working hours.",
      "2. Rank tasks by deadline and importance, and estimate a realistic duration for each.",
      "3. Place tasks into day-by-day blocks around the fixed appointments, leaving buffer time.",
      "4. Present the schedule with what was deferred and why, plus what to drop if the week overruns.",
      "",
      "## Guardrails",
      "- Do not overfill a day; keep buffer time visible instead of hiding it.",
      "- Never change or cancel appointments without explicit confirmation.",
    ],
    positives: [
      "Plan my week from this task list and these three fixed appointments.",
      "Lay out a realistic schedule for Monday to Friday around these deadlines.",
      "Which of these tasks should I do each day next week?",
    ],
    negatives: [
      "Find three times for a 30 minute meeting with a client.",
      "Sort my unread email by urgency.",
      "Turn these meeting notes into action items.",
    ],
  }),
  skill({
    id: "meeting-notes-actions",
    name: "meeting-notes-actions",
    description: "Convert meeting notes or transcripts into minutes, decisions, and owned action items with due dates.",
    category: "meetings",
    tags: ["minutes", "action-items", "transcripts"],
    sourcePrompt: "Create a meeting notes skill that turns raw notes into minutes and action items.",
    authoredAt: EXPANSION_AUTHORED_AT,
    body: [
      "## When to use",
      "Use this skill when the user supplies meeting notes, a transcript, or a call summary and wants minutes, decisions, or action items.",
      "",
      "Do not use it for scheduling the next meeting, planning a weekly agenda, or drafting outbound customer messages.",
      "",
      "## Workflow",
      "1. Read the notes and identify attendees, topics, decisions, and commitments.",
      "2. Convert each commitment into an action item with an owner and a due date when stated.",
      "3. Mark unowned or undated items as open questions instead of guessing.",
      "4. Present concise minutes with decisions first, then action items, then open questions.",
      "",
      "## Guardrails",
      "- Do not invent owners, dates, or decisions that are not in the notes.",
      "- Quote contentious statements exactly rather than paraphrasing them.",
    ],
    positives: [
      "Turn these meeting notes into minutes with action items.",
      "Pull the decisions and owners out of yesterday's call transcript.",
      "Who owns what after this project meeting?",
    ],
    negatives: [
      "Schedule the follow-up meeting for next Tuesday.",
      "Plan my week around these deadlines.",
      "Draft a follow-up email to the customer we met.",
    ],
  }),
  skill({
    id: "travel-itinerary-planner",
    name: "travel-itinerary-planner",
    description: "Plan a business trip itinerary from destination, dates, meetings, budget, and traveller preferences.",
    category: "travel",
    tags: ["itineraries", "business-travel", "trip-planning"],
    sourcePrompt: "Create a business travel itinerary planning skill.",
    authoredAt: EXPANSION_AUTHORED_AT,
    body: [
      "## When to use",
      "Use this skill when the user wants a trip itinerary or travel plan built from destination, dates, commitments, and budget.",
      "",
      "Do not use it for booking or paying for anything, arranging a single meeting time, or logging travel expenses afterwards.",
      "",
      "## Workflow",
      "1. Read the destination, dates, fixed commitments, budget, and traveller preferences.",
      "2. Draft a day-by-day itinerary with travel legs, accommodation windows, and buffer time between commitments.",
      "3. Flag tight connections, timezone changes, and anything that depends on availability.",
      "4. Present the itinerary with an ordered to-book list the user can act on.",
      "",
      "## Guardrails",
      "- Never claim a booking has been made; the plan is a proposal only.",
      "- Do not invent prices, opening hours, or availability; mark them as to-confirm.",
    ],
    positives: [
      "Plan a two day trip to Sydney around these client meetings.",
      "Build an itinerary for the trade show week within this budget.",
      "Lay out travel and hotel plans for my Melbourne visit next month.",
    ],
    negatives: [
      "Find a time for a 30 minute call with the supplier.",
      "Categorise this pile of travel expenses for reimbursement.",
      "Write a social post about our conference booth.",
    ],
  }),
  skill({
    id: "status-report-drafter",
    name: "status-report-drafter",
    description: "Draft weekly status updates and progress reports from working notes, task lists, and metrics.",
    category: "writing",
    tags: ["status-updates", "progress-reports", "reporting"],
    sourcePrompt: "Create a status report drafting skill for teams and client updates.",
    authoredAt: EXPANSION_AUTHORED_AT,
    body: [
      "## When to use",
      "Use this skill when the user wants a status update, progress report, or team update drafted from notes, task lists, or metrics.",
      "",
      "Do not use it for one-to-one customer follow-up messages, meeting minutes, or public marketing copy.",
      "",
      "## Workflow",
      "1. Read the notes and identify progress, blockers, decisions needed, and next steps.",
      "2. Draft the report with headline progress first, then risks and blockers, then asks.",
      "3. Match the register to the audience, whether client-facing, team-facing, or leadership.",
      "4. List gaps the user should fill before sending, such as missing metrics or dates.",
      "",
      "## Guardrails",
      "- Do not soften or hide blockers; state them plainly with what is needed.",
      "- Never invent metrics or completion percentages.",
    ],
    positives: [
      "Draft this week's status update from my project notes.",
      "Turn these bullet points into a progress report for the client.",
      "Write a short team update covering what shipped and what is blocked.",
    ],
    negatives: [
      "Write a follow-up message to the customer who missed our demo.",
      "Turn these meeting notes into action items.",
      "Draft three captions for our product launch.",
    ],
  }),
  skill({
    id: "procedure-writer",
    name: "procedure-writer",
    description: "Draft a step-by-step procedure from how-we-do-it notes so staff can follow it without supervision.",
    category: "operations",
    tags: ["procedures", "sops", "checklists"],
    sourcePrompt: "Create a standard-operating-procedure writing skill for small teams.",
    authoredAt: EXPANSION_AUTHORED_AT,
    body: [
      "## When to use",
      "Use this skill when the user wants working knowledge turned into a written procedure, checklist, or how-to for staff.",
      "",
      "Do not use it for summarising an existing policy document, drafting a job posting, or planning a project.",
      "",
      "## Workflow",
      "1. Read the notes and identify the goal, the trigger, the steps, and who performs them.",
      "2. Draft numbered steps with one action each, in the order a new starter would do them.",
      "3. Add checks, common mistakes, and what to do when a step fails.",
      "4. End with a short list of questions where the notes were ambiguous.",
      "",
      "## Guardrails",
      "- Do not fill gaps in the process with plausible guesses; ask instead.",
      "- Keep safety-critical steps exactly as the user described them.",
    ],
    positives: [
      "Turn these notes into a written procedure for closing the shop.",
      "Draft a step-by-step checklist for handling refunds.",
      "Write up our stocktake process so new staff can follow it.",
    ],
    negatives: [
      "Summarise this leave policy into manager obligations.",
      "Create an onboarding plan for our new hire.",
      "Draft a job ad for a cafe manager.",
    ],
  }),
  skill({
    id: "customer-feedback-themes",
    name: "customer-feedback-themes",
    description: "Analyze customer reviews, survey responses, and support messages into recurring themes and next actions.",
    category: "analysis",
    tags: ["customer-feedback", "reviews", "surveys"],
    sourcePrompt: "Create a customer feedback analysis skill for reviews and surveys.",
    authoredAt: EXPANSION_AUTHORED_AT,
    body: [
      "## When to use",
      "Use this skill when the user supplies reviews, survey responses, or support messages and wants the recurring themes and what to do about them.",
      "",
      "Do not use it for drafting replies to individual customers, designing an extraction schema, or writing marketing copy.",
      "",
      "## Workflow",
      "1. Read the feedback and group it into recurring themes with rough counts.",
      "2. Separate complaints, praise, and feature requests within each theme.",
      "3. Quote one or two representative comments per theme, anonymised.",
      "4. Present the themes ranked by frequency with a suggested next action for each.",
      "",
      "## Guardrails",
      "- Do not present a single loud comment as a trend; keep counts honest.",
      "- Remove names and contact details from quoted feedback.",
    ],
    positives: [
      "What themes come out of these customer reviews?",
      "Group this survey feedback into complaints, praise, and requests.",
      "Analyze these support messages for recurring issues.",
    ],
    negatives: [
      "Write a reply to this unhappy customer.",
      "Design a schema to extract fields from these feedback forms.",
      "Draft a social post about our five star reviews.",
    ],
  }),
  skill({
    id: "vendor-comparison",
    name: "vendor-comparison",
    description: "Review competing vendor quotes or product options into a side-by-side comparison and a recommendation.",
    category: "operations",
    tags: ["vendors", "quotes", "purchasing"],
    sourcePrompt: "Create a vendor and quote comparison skill for purchasing decisions.",
    authoredAt: EXPANSION_AUTHORED_AT,
    body: [
      "## When to use",
      "Use this skill when the user has two or more quotes, proposals, or product options and wants a structured comparison or recommendation.",
      "",
      "Do not use it for spotting legal risks in a single contract, drafting an invoice, or negotiating on the user's behalf.",
      "",
      "## Workflow",
      "1. Read each option and identify price, inclusions, terms, support, and switching costs.",
      "2. Build a side-by-side comparison on the criteria that matter to the user's stated goal.",
      "3. Note where options are not directly comparable and what is missing from each quote.",
      "4. Recommend one option with the trade-offs stated, plus questions to ask before deciding.",
      "",
      "## Guardrails",
      "- Do not invent pricing or terms that are not in the supplied material.",
      "- State when the options are too different to compare fairly.",
    ],
    positives: [
      "Compare these three supplier quotes and recommend one.",
      "Which of these two software options fits our team better?",
      "Review these contractor proposals side by side.",
    ],
    negatives: [
      "Review this contract excerpt for risky clauses.",
      "Draft an invoice for this month's consulting work.",
      "Log these supplier receipts as expenses.",
    ],
  }),
  skill({
    id: "proofread-polish",
    name: "proofread-polish",
    description: "Edit business writing for clarity, tone, grammar, and structure while preserving the original meaning.",
    category: "writing",
    tags: ["editing", "proofreading", "clarity"],
    sourcePrompt: "Create a proofreading and editing skill for everyday business writing.",
    authoredAt: EXPANSION_AUTHORED_AT,
    body: [
      "## When to use",
      "Use this skill when the user supplies existing text, such as an email, proposal, page, or notice, and wants it proofread, tightened, or reworded.",
      "",
      "Do not use it for drafting a new message from scratch, translating between languages, or reviewing legal wording.",
      "",
      "## Workflow",
      "1. Read the text and note the audience, purpose, and intended tone.",
      "2. Fix grammar, spelling, and punctuation without changing the meaning.",
      "3. Tighten wording and restructure sentences that are hard to follow.",
      "4. Return the edited text plus a short list of the significant changes.",
      "",
      "## Guardrails",
      "- Preserve factual claims, names, and figures exactly as written.",
      "- Flag ambiguity for the author instead of silently resolving it.",
    ],
    positives: [
      "Proofread this proposal for tone and typos.",
      "Tighten this email so it reads professionally.",
      "Edit this services page copy for clarity.",
    ],
    negatives: [
      "Write a follow-up email to a customer who missed our demo.",
      "Summarise this procedure document for managers.",
      "Draft three caption options for our winter sale.",
    ],
  }),
  skill({
    id: "onboarding-plan-builder",
    name: "onboarding-plan-builder",
    description: "Create a first-weeks onboarding plan for a new hire with ordered tasks, owners, and checkpoints.",
    category: "hiring",
    tags: ["onboarding", "new-hires", "training"],
    sourcePrompt: "Create a new-hire onboarding planning skill for small teams.",
    authoredAt: EXPANSION_AUTHORED_AT,
    body: [
      "## When to use",
      "Use this skill when the user wants an onboarding plan, first-week schedule, or training checklist for a new hire.",
      "",
      "Do not use it for writing the job posting, screening candidates, or documenting a single operating procedure.",
      "",
      "## Workflow",
      "1. Read the role, start date, team context, and any required training or compliance items.",
      "2. Draft an ordered plan across the first days and weeks, from introductions through to real tasks.",
      "3. Assign each item an owner and a checkpoint where progress is reviewed.",
      "4. List what the user must prepare before day one.",
      "",
      "## Guardrails",
      "- Do not invent compliance or training requirements; mark them as to-confirm.",
      "- Keep the early days light enough that a real person can absorb them.",
    ],
    positives: [
      "Create an onboarding plan for our new barista.",
      "Draft a first two weeks checklist for the office manager we just hired.",
      "Plan the training schedule for a junior technician starting Monday.",
    ],
    negatives: [
      "Draft a job ad for a part-time operations assistant.",
      "Write up our stocktake process as a step-by-step procedure.",
      "Summarise this leave policy for managers.",
    ],
  }),
  skill({
    id: "faq-drafter",
    name: "faq-drafter",
    description: "Draft FAQ entries and reusable answers from recurring customer questions and existing business detail.",
    category: "customer-support",
    tags: ["faq", "canned-answers", "self-service"],
    sourcePrompt: "Create an FAQ drafting skill built from recurring customer questions.",
    authoredAt: EXPANSION_AUTHORED_AT,
    body: [
      "## When to use",
      "Use this skill when the user wants recurring customer questions turned into an FAQ page or a set of reusable answers.",
      "",
      "Do not use it for replying to one specific customer, summarising internal policy for staff, or writing promotional copy.",
      "",
      "## Workflow",
      "1. Read the questions and group duplicates into one canonical question each.",
      "2. Draft a short, plain-language answer per question from the supplied business detail.",
      "3. Mark answers that need a fact the user has not supplied, such as pricing or hours.",
      "4. Order the entries from most to least common and suggest ones worth adding.",
      "",
      "## Guardrails",
      "- Do not invent prices, policies, or commitments; leave a clear placeholder instead.",
      "- Keep answers short enough to paste into chat or a website.",
    ],
    positives: [
      "Turn these common customer questions into an FAQ page.",
      "Draft reusable answers for the questions our support inbox gets weekly.",
      "Create an FAQ for our new booking system from these notes.",
    ],
    negatives: [
      "Write a reply to this specific customer complaint.",
      "Summarise our refund policy into staff obligations.",
      "Write an Instagram caption announcing new opening hours.",
    ],
  }),
] as const satisfies readonly CorpusSeed[];

export const baselineSkillCorpus: readonly BaselineSkillCorpusEntry[] = seeds.map((entry) => ({
  ...entry,
  contentHash: sha256(entry.source),
}));

export const baselineDistractors = baselineSkillCorpus.map(({ name, description }) => ({
  name,
  description,
}));

function skill(input: {
  readonly id: string;
  readonly name: string;
  readonly description: string;
  readonly category: SkillCategory;
  readonly tags: readonly string[];
  readonly sourcePrompt: string;
  readonly authoredAt?: string;
  readonly body: readonly string[];
  readonly positives: readonly string[];
  readonly negatives: readonly string[];
}): CorpusSeed {
  return {
    id: input.id,
    version: 1,
    name: input.name,
    description: input.description,
    source: `---\nname: ${input.name}\ndescription: ${input.description}\ncategory: ${input.category}\ntags:\n${input.tags.map((tag) => `  - ${tag}`).join("\n")}\n---\n\n${input.body.join("\n")}\n`,
    promptBattery: [
      ...input.positives.map((prompt) => ({ prompt, expected: "fire" as const })),
      ...input.negatives.map((prompt) => ({ prompt, expected: "silent" as const })),
    ],
    provenance: {
      authoringTool: AUTHORING_TOOL,
      authoredAt: input.authoredAt ?? AUTHORED_AT,
      sourcePrompt: input.sourcePrompt,
    },
  };
}

function sha256(value: string): string {
  return createHash("sha256").update(value).digest("hex");
}
